language: ruby
sudo: required
addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty universe"
    packages:
      - haveged
services:
  - docker
cache:
  bundler: true
  directories:
    - $HOME/.m2
before_script:
  - docker-compose up -d
script: bundle exec rake
rvm:
  - jruby-9.1.2.0
  - jruby-1.7
